<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_kru.ac.inKrishna University</name>
   <tag></tag>
   <elementGuidId>7849b01e-453c-4666-8adc-c0565104229a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-ib.fz-20.lh-26.td-hu.tc.va-bot.mxw-100p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>426d7a31-3796-4d93-94ad-92d7e598c360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>95af5e0f-2bb2-45fe-b122-6c3127401bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>5c6ebeeb-d615-4e14-a83d-450512fdd98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a6208bc3-69e2-4243-b06d-ac99d32e0e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>67d24ff9-9be6-4d88-8532-4be4f9a5694e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kru.ac.in/</value>
      <webElementGuid>1b05e98d-5e26-4b3a-990a-b5e792462dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-910</name>
      <type>Main</type>
      <value>60f0b2a49e0698</value>
      <webElementGuid>eabc62ca-a831-447d-850b-02e13374f8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Krishna University</value>
      <webElementGuid>fcef7c85-139f-45e9-9260-8758be776a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kru.ac.inKrishna University</value>
      <webElementGuid>7877412c-d9e3-424f-add4-5ab58c95ddad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg  searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd fst algo algo-sr relsrch Sr&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>6caef35a-2720-4183-948d-c9fcac6309a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>f2fa7bf4-5a50-44ee-b115-b1cf6fd7d510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kru.ac.in/')]</value>
      <webElementGuid>6a3fab92-5d25-441b-b9f5-7ed202fbdb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>dafc7229-232b-4bf7-8ee3-31221b10d851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kru.ac.in/' and (text() = 'kru.ac.inKrishna University' or . = 'kru.ac.inKrishna University')]</value>
      <webElementGuid>bea883b7-7b82-437c-b064-916bcd2544cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
