<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_c-j5spuaso9wxy</name>
   <tag></tag>
   <elementGuidId>0ea7c485-88ef-47d5-8438-a4c41950f5c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-j5spuaso9wxy&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-j5spuaso9wxy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>88b3980b-24a7-456a-a55f-4981da31c405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>0ff5717a-c330-4ad0-9f20-de5f085b41df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-j5spuaso9wxy</value>
      <webElementGuid>558f7c13-2c0d-4974-8ef0-35eb20f34612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d2da46f8-593b-45fb-883c-c67fe755b106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>add8ed6c-e8a4-4cc3-b770-d21317eb1e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>ca117715-c9fe-4db7-b959-fb8719258b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>ce895f5a-95ea-4c50-a8dc-63e4547e0b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[4]/iframe[1]</value>
      <webElementGuid>46847e3d-12a4-47b7-907e-2c67e86b4d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-j5spuaso9wxy']</value>
      <webElementGuid>7f38d38b-66c7-4f66-89c6-7704951b15ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>26c68e12-1652-48d2-86df-08edc10fe9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-j5spuaso9wxy' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>37dcfdb7-74a7-41a5-a692-e0b6a3c22abb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
