<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-j5spuaso9wxy</name>
   <tag></tag>
   <elementGuidId>e8cdfb62-6f8f-4ec4-9c62-f34e55e69634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-j5spuaso9wxy&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-j5spuaso9wxy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>09beebdb-26d9-463c-b147-8ec366b87b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>194abb88-6831-497d-acec-a82da0de2281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>5f8028c3-9bab-45d6-ae7a-b8164696ef80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>83501024-d79a-4921-b2d5-5d7bae6d2a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>003e83b1-3dc7-4370-835b-afd47207285e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-j5spuaso9wxy</value>
      <webElementGuid>3bb74b2c-c90f-44e8-9c02-f16a93991673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2de7da3a-d7a6-41d0-8f9a-3c86211c82a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>94bdbfd7-959f-47a5-99f8-8f2bd833ef39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>61bff914-0af3-4f04-a304-4c727a00b4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;size=normal&amp;s=RbRFi8FLYuKbXAf3g12F-79iRl2VjTm_676Lc2A1KkgYx3je0alFuMoAHGKWqlRae7D4k1Zfhemx7qxHfw3zxQqzNyawn3dxR720fjGl5tlmcavj_DFE_dEp2s-IcUQzTEf4vDKfvFD96g-f7G6WMruSMgoHSy9CeeC3yVBVRMyFjXtb5U2SY7T5uIwGsQG8VFtKipxYWO_y69JAEjAIsw4H9-zrBhroOCdy5nau6COlVH8kgmUPuwMhP3ugiAu459S6RltBY6t9uc5UT1lsVjyx3F7miCE&amp;cb=olb1lje0icty</value>
      <webElementGuid>52dd5059-0332-4758-8bf9-f43a0b6094bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>893e3d4a-d586-4d22-a7bf-b9a8d9c4575a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-j5spuaso9wxy']</value>
      <webElementGuid>6642994b-2fe8-4be6-a69c-9ff2ff166978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>d0fbc950-3200-41e5-83f2-1bdbf0205215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fa7eaee2-2ba0-4456-851b-fc0336f6c9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-j5spuaso9wxy' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=Ya-Cd6PbRI5ktAHEhm9JuKEu&amp;size=normal&amp;s=RbRFi8FLYuKbXAf3g12F-79iRl2VjTm_676Lc2A1KkgYx3je0alFuMoAHGKWqlRae7D4k1Zfhemx7qxHfw3zxQqzNyawn3dxR720fjGl5tlmcavj_DFE_dEp2s-IcUQzTEf4vDKfvFD96g-f7G6WMruSMgoHSy9CeeC3yVBVRMyFjXtb5U2SY7T5uIwGsQG8VFtKipxYWO_y69JAEjAIsw4H9-zrBhroOCdy5nau6COlVH8kgmUPuwMhP3ugiAu459S6RltBY6t9uc5UT1lsVjyx3F7miCE&amp;cb=olb1lje0icty']</value>
      <webElementGuid>04d26c48-0ca3-44eb-971f-2738b34a4812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
